#!/bin/sh
#
# fluxbox startup-script:
#
# Lines starting with a '#' are ignored.

# Transparency
xcompmgr -c &

# Screensaver
xscreensaver -no-splash &

# Background
fbsetbg -a `tail -n 1 .fluxbox/lastwallpaper|cut -d'|' -f 2`

# Applets
blueman-applet&
pasystray &
nm-applet &

# Disable bell
xset -b

# Defaults Apps
spotify &
brscan-skey &
owncloud &

# SSH
ssh-add &

which fbautostart > /dev/null
if [ $? -eq 0 ]; then
    fbautostart
fi

exec fluxbox
